CREATE DATABASE final_test;
CREATE USER 'tester'@'localhost' IDENTIFIED BY 'password';
GRANT CREATE, ALTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD on *.* TO 'tester'@'localhost' WITH GRANT OPTION;
FLUSH PRIVILEGES;